# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Workflow

on:
  pull_request:
    branches:
      - master
      - release-1.x
env:
  SELENIUM_GRID_PROVIDER: saucelabs
  CLOUD_WATCH_METRIC: false
  TEST_TYPE: Github-Action
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run build:release

  check_integ_test_required:
    name: Check if Integ Tests are Required
    needs: build
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    outputs:
      integration_test_required: ${{ steps.integration_test_required.outputs.needs_integration_test }}

    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if Integ Tests need to Run
        run: node script/needs-integration-test.js
      - name: Set integration test requirement to true if necessary
        id: integration_test_required
        if: ${{ success() }}
        run: echo '::set-output name=needs_integration_test::true'

  integ-audio:
    name: Audio Integration Test
    needs: check_integ_test_required
    if: ${{needs.check_integ_test_required.outputs.integration_test_required}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Audio Integration Test
        run: npm run test:integration-audio

  integ-screen-share:
    name: Screen Share Integration Test
    needs: check_integ_test_required
    if: needs.check_integ_test_required.outputs.integration_test_required && github.event.pull_request.base.ref == 'release-1.x'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Screen Share Integration Test
        run: npm run test:integration-screen-share

  integ-video:
    name: Video Integration Test
    needs: integ-audio
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Video Integ Test
        run: npm run test:integration-video

  integ-content-share:
    name: Content Share Integration Test
    needs: integ-audio
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Content Share Integration Test
        run: npm run test:integration-content-share


  integ-data-message:
    name: Data Message Integration Test
    needs: integ-video
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Data Message Integration Test
        run: npm run test:integration-data-message


  integ-meeting-end:
    name: Meeting End Integration Test
    needs: integ-video
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Meeting End Integ Test
        run: npm run test:integration-meeting-end

  integ-meeting-readiness:
    name: Meeting Readiness Integration Test
    needs: integ-video
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Create a Job ID
        id: create-job-id
        uses: filipstefansson/uuid-action@v1
      - name: Set JOB_ID Env Variable
        run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
      - name: Echo Job ID
        run: echo "${{ steps.create-job-id.outputs.uuid }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Sauce Connect
        uses: saucelabs/sauce-connect-action@master
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          noSSLBumpDomains: all
          tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
      - name: Checkout Chime SDK Repo
        uses: actions/checkout@v2
      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Kite
        run: integration/js/script/install-kite
      - name: Clean Install
        run: npm ci
      - name: Run Meeting Readiness Checker Integration Test
        run: npm run test:integration-meeting-readiness-checker